# Azure Pipelines configuration that builds and packages the extension.
# To learn more about Azure Pipelines: https://aka.ms/learn-azure-pipelines
trigger:
  - master
  
jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: azure-pipelines-steps.yml
  